"""Future model plugin contract only. No agent/model implementation is supplied."""
from typing import Protocol, Mapping, Any
from .contracts import ControlCommand, SimulationFrame


class DrivingAgent(Protocol):
    def initialize(self, config: Mapping[str, Any]) -> None: ...
    def reset(self) -> None: ...
    def process_observation(self, observation: SimulationFrame) -> None: ...
    def get_control(self) -> ControlCommand | None: ...
    def shutdown(self) -> None: ...
