"""Application boundary: no rendering or locally simulated vehicle state."""
from typing import Protocol


class SimulationProvider(Protocol):
    name: str
    def connect(self): ...
    def disconnect(self): ...
    def is_connected(self) -> bool: ...
    def load_world(self, map_name: str): ...
    def reset_world(self): ...
    def spawn_ego_vehicle(self): ...
    def destroy_ego_vehicle(self): ...
    def set_throttle(self, value: float): ...
    def set_brake(self, value: float): ...
    def set_steering(self, value: float): ...
    def set_reverse(self, reverse: bool): ...
    def set_handbrake(self, enabled: bool): ...
    def set_controls(self, **controls): ...
    def step(self) -> dict: ...
    def get_vehicle_state(self) -> dict: ...
    def get_sensor_state(self) -> dict: ...
    def get_world_state(self) -> dict: ...
    def get_camera_frame(self): ...
    def reset_vehicle(self): ...
    def set_paused(self, paused: bool): ...
    def close(self): ...
